#los datos de prueba van a quedar asi hasta que tenga una idea clara de como usar el json
biblioteca = [
  {"titulo": "Bohemian Rhapsody", "artista": "Queen", "genero": "Rock", "letra": "Is this real", "calificacion": 5},
  {"titulo": "Hotel California", "artista": "Eagles", "genero": "Rock", "letra": "On a dark", "calificacion": 5},
  {"titulo": "Sweet Child O Mine", "artista": "Guns N Roses", "genero": "Rock", "letra": "She has got", "calificacion": 4},
  {"titulo": "Imagine", "artista": "John Lennon", "genero": "Pop", "letra": "Imagine all people", "calificacion": 5},
  {"titulo": "Billie Jean", "artista": "Michael Jackson", "genero": "Pop", "letra": "She was more", "calificacion": 5},
  {"titulo": "Smells Like Teen Spirit", "artista": "Nirvana", "genero": "Grunge", "letra": "With the lights", "calificacion": 4},
  {"titulo": "Back in Black", "artista": "AC/DC", "genero": "Rock", "letra": "Back in black", "calificacion": 4},
  {"titulo": "Shape of You", "artista": "Ed Sheeran", "genero": "Pop", "letra": "The club isn't", "calificacion": 3},
  {"titulo": "Blinding Lights", "artista": "The Weeknd", "genero": "Synthpop", "letra": "I've been on", "calificacion": 5},
  {"titulo": "Despacito", "artista": "Luis Fonsi", "genero": "Reggaeton", "letra": "Sí, sabes que", "calificacion": 2},
  {"titulo": "De Música Ligera", "artista": "Soda Stereo", "genero": "Rock Español", "letra": "Ella durmió al", "calificacion": 5},
  {"titulo": "Matador", "artista": "Los Fabulosos Cadillacs", "genero": "Ska", "letra": "Te están buscando", "calificacion": 4},
  {"titulo": "Lamento Boliviano", "artista": "Los Enanitos Verdes", "genero": "Rock Español", "letra": "Me quieren agitar", "calificacion": 4},
  {"titulo": "La Incondicional", "artista": "Luis Miguel", "genero": "Balada", "letra": "Tú, la misma", "calificacion": 5},
  {"titulo": "Rayando el Sol", "artista": "Maná", "genero": "Rock Español", "letra": "Rayando el sol", "calificacion": 3},
  {"titulo": "Flaca", "artista": "Andrés Calamaro", "genero": "Rock Español", "letra": "Flaca, no me", "calificacion": 4},
  {"titulo": "Tren al Sur", "artista": "Los Prisioneros", "genero": "Synthpop", "letra": "Siete y media", "calificacion": 5},
  {"titulo": "Mil Horas", "artista": "Los Abuelos de la Nada", "genero": "Rock Español", "letra": "Hace frío y", "calificacion": 5},
  {"titulo": "Crimen", "artista": "Gustavo Cerati", "genero": "Rock Español", "letra": "La espera me", "calificacion": 5},
  {"titulo": "Tratame Suavemente", "artista": "Soda Stereo", "genero": "Rock Español", "letra": "Alguien me dijo", "calificacion": 4},
  {"titulo": "Stayin Alive", "artista": "Bee Gees", "genero": "Disco", "letra": "Well you can", "calificacion": 4},
  {"titulo": "Wonderwall", "artista": "Oasis", "genero": "Britpop", "letra": "Today is gonna", "calificacion": 4},
  {"titulo": "Stairway to Heaven", "artista": "Led Zeppelin", "genero": "Rock", "letra": "There's a lady", "calificacion": 5},
  {"titulo": "Thunderstruck", "artista": "AC/DC", "genero": "Rock", "letra": "Thunder, thunder, thunder", "calificacion": 4},
  {"titulo": "Sweet Home Alabama", "artista": "Lynyrd Skynyrd", "genero": "Rock", "letra": "Big wheels keep", "calificacion": 4},
  {"titulo": "Take On Me", "artista": "A-ha", "genero": "Synthpop", "letra": "Talking away, I", "calificacion": 5},
  {"titulo": "Smooth", "artista": "Santana", "genero": "Rock Latino", "letra": "Man, it's a", "calificacion": 4},
  {"titulo": "Clocks", "artista": "Coldplay", "genero": "Alternative", "letra": "Lights go out", "calificacion": 4},
  {"titulo": "Uptown Funk", "artista": "Bruno Mars", "genero": "Funk", "letra": "This hit, that", "calificacion": 4},
  {"titulo": "Rolling in the Deep", "artista": "Adele", "genero": "Soul", "letra": "There's a fire", "calificacion": 5},
  {"titulo": "Bad Guy", "artista": "Billie Eilish", "genero": "Pop", "letra": "White shirt now", "calificacion": 3},
  {"titulo": "Radioactive", "artista": "Imagine Dragons", "genero": "Rock", "letra": "I'm waking up", "calificacion": 4},
  {"titulo": "Counting Stars", "artista": "OneRepublic", "genero": "Pop", "letra": "Lately I've been", "calificacion": 4},
  {"titulo": "Sugar", "artista": "Maroon 5", "genero": "Pop", "letra": "I'm hurt, I'm", "calificacion": 3},
  {"titulo": "Havana", "artista": "Camila Cabello", "genero": "Pop", "letra": "Havana, ooh na-na", "calificacion": 3},
  {"titulo": "Starboy", "artista": "The Weeknd", "genero": "R&B", "letra": "I'm tryna put", "calificacion": 4},
  {"titulo": "Riptide", "artista": "Vance Joy", "genero": "Indie", "letra": "I was scared", "calificacion": 4},
  {"titulo": "Demonio", "artista": "Imagine Dragons", "genero": "Rock", "letra": "When the days", "calificacion": 4},
  {"titulo": "Yellow", "artista": "Coldplay", "genero": "Alternative", "letra": "Look at stars", "calificacion": 5},
  {"titulo": "Hey Jude", "artista": "The Beatles", "genero": "Rock", "letra": "Hey Jude, don't", "calificacion": 5},
  {"titulo": "Yesterday", "artista": "The Beatles", "genero": "Pop", "letra": "Yesterday, all my", "calificacion": 5},
  {"titulo": "Let It Be", "artista": "The Beatles", "genero": "Rock", "letra": "When I find", "calificacion": 5},
  {"titulo": "Come Together", "artista": "The Beatles", "genero": "Rock", "letra": "Here come old", "calificacion": 4},
  {"titulo": "Smooth Criminal", "artista": "Michael Jackson", "genero": "Pop", "letra": "As he came", "calificacion": 5},
  {"titulo": "Thriller", "artista": "Michael Jackson", "genero": "Pop", "letra": "It's close to", "calificacion": 5},
  {"titulo": "Beat It", "artista": "Michael Jackson", "genero": "Pop", "letra": "They told him", "calificacion": 5},
  {"titulo": "Toxic", "artista": "Britney Spears", "genero": "Pop", "letra": "Baby, can't you", "calificacion": 4},
  {"titulo": "Vogue", "artista": "Madonna", "genero": "Pop", "letra": "Strike a pose", "calificacion": 4},
  {"titulo": "Like a Virgin", "artista": "Madonna", "genero": "Pop", "letra": "I made it", "calificacion": 4},
  {"titulo": "En la Ciudad de la Furia", "artista": "Soda Stereo", "genero": "Rock Español", "letra": "Me verás volar", "calificacion": 5}
]
